import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { AlertProvider } from '../store/AlertContext';
import { NavigationMainMenu } from '@/components/NavigationMainMenu';
import { AlertComponent } from '@/components/AlertComponent';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <AlertProvider>
                    <div className='grid grid-rows-[80px_1fr] md:grid-rows-[200px_1fr] grid-cols-1 h-screen justify-center items-center'>
                        <NavigationMainMenu />

                        <main className='self-start flex flex-col md:flex-row justify-center items-stretch gap-6 md:w-[1200px] mt-4 md:mt-10 mx-auto p-4 pt-0'>
                            {children}
                        </main>
                    </div>

                    <AlertComponent />
                </AlertProvider>
            </body>
        </html>
    );
}
